// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mysite.roospring.domain;

import com.mysite.roospring.domain.ProfileDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProfileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProfileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProfileIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProfileIntegrationTest: @Transactional;
    
    @Autowired
    private ProfileDataOnDemand ProfileIntegrationTest.dod;
    
    @Test
    public void ProfileIntegrationTest.testCountProfiles() {
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", dod.getRandomProfile());
        long count = com.mysite.roospring.domain.Profile.countProfiles();
        org.junit.Assert.assertTrue("Counter for 'Profile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProfileIntegrationTest.testFindProfile() {
        com.mysite.roospring.domain.Profile obj = dod.getRandomProfile();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to provide an identifier", id);
        obj = com.mysite.roospring.domain.Profile.findProfile(id);
        org.junit.Assert.assertNotNull("Find method for 'Profile' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Profile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProfileIntegrationTest.testFindAllProfiles() {
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", dod.getRandomProfile());
        long count = com.mysite.roospring.domain.Profile.countProfiles();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Profile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.mysite.roospring.domain.Profile> result = com.mysite.roospring.domain.Profile.findAllProfiles();
        org.junit.Assert.assertNotNull("Find all method for 'Profile' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Profile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProfileIntegrationTest.testFindProfileEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", dod.getRandomProfile());
        long count = com.mysite.roospring.domain.Profile.countProfiles();
        if (count > 20) count = 20;
        java.util.List<com.mysite.roospring.domain.Profile> result = com.mysite.roospring.domain.Profile.findProfileEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Profile' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Profile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProfileIntegrationTest.testFlush() {
        com.mysite.roospring.domain.Profile obj = dod.getRandomProfile();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to provide an identifier", id);
        obj = com.mysite.roospring.domain.Profile.findProfile(id);
        org.junit.Assert.assertNotNull("Find method for 'Profile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProfile(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Profile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProfileIntegrationTest.testMerge() {
        com.mysite.roospring.domain.Profile obj = dod.getRandomProfile();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to provide an identifier", id);
        obj = com.mysite.roospring.domain.Profile.findProfile(id);
        boolean modified =  dod.modifyProfile(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.mysite.roospring.domain.Profile merged = (com.mysite.roospring.domain.Profile) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Profile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProfileIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", dod.getRandomProfile());
        com.mysite.roospring.domain.Profile obj = dod.getNewTransientProfile(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Profile' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Profile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProfileIntegrationTest.testRemove() {
        com.mysite.roospring.domain.Profile obj = dod.getRandomProfile();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Profile' failed to provide an identifier", id);
        obj = com.mysite.roospring.domain.Profile.findProfile(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Profile' with identifier '" + id + "'", com.mysite.roospring.domain.Profile.findProfile(id));
    }
    
}
