package com.truward.gbp.shared.service;

import com.google.gwt.user.client.rpc.IsSerializable;

/**
 * Base class for all the responses to service requests,
 * all the responses generally are generated by server.
 * This is a part of service request-response framework.
 */
public interface ServiceResponse extends IsSerializable {
}

