// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.truward.rsw.domain;

import java.lang.String;

privileged aspect UserRole_Roo_JavaBean {
    
    public String UserRole.getName() {
        return this.name;
    }
    
    public void UserRole.setName(String name) {
        this.name = name;
    }
    
}
