-- DB schema


create table USER_ACCOUNT (
  ID bigint generated by default as identity primary key,

  LOGIN varchar(256) not null,

  PASSWORD varchar(256) not null,

  EMAIL varchar(128) not null,

  AVATAR_URL varchar(256),

  CREATED timestamp not null
);

create table ROLE (
  ID bigint generated by default as identity primary key,
  ROLE_NAME varchar(32) not null
);

create table USER_ROLES (
  USER_ID bigint not null,
  ROLE_ID bigint not null
);


create table BLOG_POST (
  ID bigint generated by default as identity primary key,

  AUTHOR_ID bigint not null,

  CREATED timestamp not null,
  TITLE varchar(256) not null,
  CONTENT varchar(4096) not null
);

create table BLOG_TAG (
  ID bigint generated by default as identity primary key,
  TAG_NAME varchar(64)
);


create table BLOG_POST_TAGS (
  POST_ID bigint not null,
  TAG_ID bigint not null
);


create table BLOG_COMMENT (
  ID bigint generated by default as identity primary key,

  AUTHOR_ID bigint not null,

  PARENT_POST_ID bigint not null,
  PARENT_COMMENT_ID bigint,

  CREATED timestamp not null,
  CONTENT varchar(4096) not null
);

-- constraints

-- USER_PROFILE table
-- alter table USER_ACCOUNT add constraint PK_USER_ACCOUNT_ID primary key (ID);

alter table USER_ACCOUNT add constraint
  UNQ_USER_ACCOUNT_LOGIN unique (LOGIN);

alter table USER_ACCOUNT add constraint
  UNQ_USER_ACCOUNT_EMAIL unique (EMAIL);

-- ROLE table
-- alter table ROLE add constraint PK_ROLE_ID primary key (ID);

alter table ROLE add constraint
  UNQ_ROLE_NAME unique (ROLE_NAME);

-- USER_ROLES table
alter table USER_ROLES add constraint
  FK_USER_ROLES_USER_ID foreign key (USER_ID) references USER_ACCOUNT(ID) on delete cascade;

alter table USER_ROLES add constraint
  FK_USER_ROLES_ROLE_ID foreign key (ROLE_ID) references ROLE(ID) on delete cascade;

-- BLOG_POST table
-- alter table BLOG_POST add constraint PK_BLOG_POST_ID primary key (ID);

alter table BLOG_POST add constraint
  FK_BLOG_POST_AUTHOR_ID foreign key (AUTHOR_ID) references USER_ACCOUNT(ID) on delete cascade;

-- BLOG_TAG table
-- alter table BLOG_TAG add constraint PK_BLOG_TAG_ID primary key (ID);

alter table BLOG_TAG add constraint
  UNQ_BLOG_TAG_NAME unique (TAG_NAME);

-- BLOG_POST_TAGS table
alter table BLOG_POST_TAGS add constraint
  PK_BLOG_POST_TAGS primary key (POST_ID, TAG_ID);

alter table BLOG_POST_TAGS add constraint
  FK_BLOG_POST_TAGS_POST_ID foreign key (POST_ID) references BLOG_POST(ID) on delete cascade;

alter table BLOG_POST_TAGS add constraint
  FK_BLOG_POST_TAGS_TAG_ID foreign key (TAG_ID) references BLOG_TAG(ID) on delete cascade;


-- BLOG_COMMENT table
alter table BLOG_COMMENT add constraint
  FK_BLOG_COMMENT_AUTHOR_ID foreign key (AUTHOR_ID) references USER_ACCOUNT(ID) on delete cascade;

alter table BLOG_COMMENT add constraint
  FK_BLOG_COMMENT_PARENT_POST_ID foreign key (PARENT_POST_ID) references BLOG_POST(ID) on delete cascade;

alter table BLOG_COMMENT add constraint
  FK_BLOG_COMMENT_PARENT_COMMENT_ID foreign key (PARENT_COMMENT_ID) references BLOG_COMMENT(ID) on delete cascade;

-- end of DB schema
