
---
--- tables
---

create memory table USER_ACCOUNT (
  ID bigint generated by default as identity primary key,

  USER_NAME varchar(64) not null,

  BALANCE decimal not null,

  CREATED timestamp not null
);

create memory table BANK_OPERATION (
  ID bigint generated by default as identity primary key,

  USER_ID bigint not null,

  AMOUNT decimal not null,

  STATUS integer not null,

  CREATED timestamp not null
);
